site_name: Marine Coders

repo_url: https://github.com/marinecoders/marinecoders.github.io
repo_name: marinecoders/marines.dev
edit_uri: ""
theme:
  icon:
    repo: fontawesome/brands/github
  custom_dir: docs/overrides
  name: material
  static_templates:
    - 404.html
  include_search_page: false
  search_index_only: true

  language: en
  features:
    - content.code.annotate
    - content.tooltips
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    
    
  palette:
    - scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
    - scheme: marinecoders-light
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

  favicon: /assets/favicon.png
  logo: /assets/logo.png

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables
  - attr_list
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - footnotes
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - blog:
      draft_if_future_date: true
      authors_file: .authors.yml
  - meta
  - search
  - tags:
      tags_file: blog/tags.md
      

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/marinecoders
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/marine-coders
      
copyright: Copyright &copy; 2022 Marine Coders

nav:
  - Marine Coders: 'https://marines.dev'
  - About: /about
  - Learn: /learn
  - Projects: /projects
  - Chat: /chat
  - Blog:
    - blog/index.md 
  - Demo: /demo