collin.chew:
  name: Capt Collin Chew
  description: Co-Founder
  avatar: https://github.com/SemperRuminare.png
drew.hutch:
  name: Maj Drew Hutcheon
  description: Co-Foudner
  avatar: https://github.com/drewhutcheon.png