collin.chew:
  name: Capt Collin Chew
  description: Co-Founder
  avatar: /assets/authors/collinchew.jpeg
drew.hutch:
  name: Maj Drew Hutcheon
  description: Co-Founder
  avatar: /assets/authors/drewhutch.jpeg
william.crum:
  name: Cpl William Crum
  description: Marine Coder
  avatar: /assets/authors/elisoncrum.jpeg
skip.mcgee:
  name: Maj Skip McGee
  description: Marine Coder
  avatar: /assets/authors/skipmcgee.jpeg
